name: Markdown lint
on: [pull_request]
jobs:
  markdownlint:
    name: markdownlint-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        id: linter
        with:
          globs: 'src/**/*.md'
          config: '.markdownlint.jsonc'      
